format:
	cargo fmt --quiet

lint:
	cargo clippy --quiet

test:
	cargo test --quiet

run:
	cargo run -- --number 3 --fruits apple --fruits cherry --fruits orange --fruits pear --fruits peach

all: format lint test run